### ISSUE TITLE
Mention about IKafkaClientFactory

### ISSUE THREAD

**Issue by SitamMatt** [halamah/aspnetcorekafka#3]
I think it will be a good idea to mention in README about possibility to configure kafka clients by yourself using existing IKafkaClientFactory interface. There are no info about such a mechanism and i think it will be useful for those who need to include sasl in their configuration.

**Comment by halamah** [comment]
Hi

isn't this something you would want to configure with appsettings like this

 `json
 "Kafka": {
    "Group": "compensations-service",
    "Producer": {
      "socket.timeout.ms": 15000,
      "message.send.max.retries": 10,
      "message.timeout.ms": 200000,
      <<add more required options>>
    },
    "Consumer": {
      "socket.timeout.ms": 15000,
      "enable.auto.commit": false,
      <<add more required options>>
    },
    "Message": {
      "Default": "offset: stored, buffer(100), commit(), options(retryFailure, skipNullMessages)"
    }
  }
`

**Comment by SitamMatt** [comment]
Sorry, you're right.
Actually, I didn't notice that the configuration is passed there as Dicitonary.
